import { Metadata } from "next";
import { ScrollReveal } from "@/components/ScrollReveal";
import LineWaves from "@/components/reactbits/LineWaves";

export const metadata: Metadata = {
  title: "Terms of Service | Holistic Health Clinic",
  description: "Terms of Service for Holistic Health Clinic.",
};

export default function TermsOfServicePage() {
  return (
    <main className="flex-1 flex flex-col bg-background pt-28 pb-24">
      <div className="container mx-auto px-6 max-w-4xl space-y-16">
        
        {/* Header */}
        <ScrollReveal animation="slide-up">
          <div className="relative py-12 px-6 text-center max-w-3xl mx-auto space-y-4 rounded-3xl overflow-hidden bg-gradient-to-br from-primary/5 to-secondary/5 border border-primary/10">
            <div className="absolute inset-0 w-full h-full pointer-events-none" style={{ zIndex: 1 }}>
              <LineWaves
                speed={0.1}
                innerLineCount={10}
                outerLineCount={15}
                warpIntensity={0.2}
                rotation={0}
                edgeFadeWidth={0.2}
                colorCycleSpeed={0.5}
                brightness={0.15}
                color1="#1886C6"
                color2="#22c55e"
                color3="#1886C6"
                enableMouseInteraction={false}
              />
            </div>
            <div className="relative z-10 space-y-2">
              <h1 className="text-4xl md:text-5xl font-extrabold text-foreground tracking-tight">Terms of Service</h1>
              <p className="text-muted-foreground font-medium">Last Updated: June 2026</p>
            </div>
          </div>
        </ScrollReveal>
        
        <div className="prose prose-slate dark:prose-invert max-w-none space-y-10 text-muted-foreground">
          <ScrollReveal animation="fade-in" delay={150}>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground">1. Agreement to Terms</h2>
          <p>
            These Terms of Service constitute a legally binding agreement made between you, whether personally or on behalf of an entity (“you”) and Holistic Health Clinic ("we," "us," or "our"), concerning your access to and use of our website as well as any other media form, media channel, mobile website or mobile application related, linked, or otherwise connected thereto.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground">2. Not Medical Advice</h2>
          <p>
            The content provided on this website, including text, graphics, images, and information generated by our AI chatbot, is for informational purposes only. It is not intended to be a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.
          </p>
          <p>
            Never disregard professional medical advice or delay in seeking it because of something you have read on this website. If you think you may have a medical emergency, call your doctor, go to the emergency department, or call emergency services immediately.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground">3. User Representations</h2>
          <p>
            By using the Site, you represent and warrant that: (1) you have the legal capacity and you agree to comply with these Terms of Service; (2) you are not a minor in the jurisdiction in which you reside; (3) you will not access the Site through automated or non-human means, whether through a bot, script or otherwise (except as expressly permitted by us); (4) you will not use the Site for any illegal or unauthorized purpose; and (5) your use of the Site will not violate any applicable law or regulation.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground">4. Submissions</h2>
          <p>
            You acknowledge and agree that any questions, comments, suggestions, ideas, feedback, or other information regarding the Site ("Submissions") provided by you to us are non-confidential and shall become our sole property. We shall own exclusive rights, including all intellectual property rights, and shall be entitled to the unrestricted use and dissemination of these Submissions for any lawful purpose, commercial or otherwise, without acknowledgment or compensation to you.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground">5. Modifications and Interruptions</h2>
          <p>
            We reserve the right to change, modify, or remove the contents of the Site at any time or for any reason at our sole discretion without notice. However, we have no obligation to update any information on our Site. We also reserve the right to modify or discontinue all or part of the Site without notice at any time.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-foreground">6. Governing Law</h2>
          <p>
            These Terms shall be governed by and defined following the laws of India. Holistic Health Clinic and yourself irrevocably consent that the courts of Mumbai, Maharashtra shall have exclusive jurisdiction to resolve any dispute which may arise in connection with these terms.
          </p>
        </section>
          </ScrollReveal>
        </div>
      </div>
    </main>
  );
}
